version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - persist_to_workspace:
          root: .
          paths:
            - .

  build_docker_image:
    docker:
      - image: cimg/go:1.17

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t blogiversal-server .

  deploy:
    docker:
      - image: cimg/go:1.18

    working_directory: ~/app

    steps:
      - checkout

      # Adding SSH keys
      - add_ssh_keys:
          fingerprints:
            - ssh-rsa 2048 SHA256:f6NjADgnNm1RQbMuvD+emI99EELu7S1EjPgGtCpiXtQ

      - run:
          name: Deploy to AWS EC2
          command: |
            scp -r / ubuntu@ip-172-31-19-115:/production
            # Replace /workspace/dist with the path to your built application files inside the Docker image
            # Replace "ubuntu" with your EC2 instance username
            # Replace "your-ec2-instance-ip" with your EC2 instance IP
            # Replace "/path/to/destination" with the destination path on the EC2 instance

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
      - deploy:
          requires:
            - build_docker_image
